# Configuration test
# Instruments that we're generating exercises for
instruments:
  - name: guitar
    clef: "treble_8"
    lower-limit: E-2
    upper-limit: E-5
  - name: bass
    clef: "bass_8"
    lower-limit: E-1
    upper-limit: G-3
  - name: violin
    clef: treble
    lower-limit: G-3
    upper-limit: C-6

# Arpeggio pattern to be used
arpeggio-pattern: "1 2 3 2 3 2 1 3"

# List of keys to be used
major-keys: "Eb C A"
minor-keys: "C A F#"

# Default is false. This is done to make it easier to remember which
# notes are sharpened/flattened in various keys.
use-key-signatures: false
